spring:
    datasource:
        password: 1111
        url: jdbc:postgresql://localhost:5432/Conflict-Forecaster-DB
        username: postgres
    jpa:
        hibernate:
            ddl-auto: update
arima:
    parameters:
        p: 3
        d: 0
        q: 3
        P: 1
        D: 1
        Q: 0
        m: 0